version: '2.3'
services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./container-files/nginx/conf.d:/etc/nginx/conf.d"
      - "./container-files/nginx/nginx.conf:/etc/nginx/nginx.conf"
